### ISSUE TITLE
Subtract - not supported for PyTorch 1.3.1

### ISSUE THREAD

**Issue by kme2698** [jongwook/onsets-and-frames#9]
Hi, really thank you for your implementation!
I use PyTorch 1.3.1 which reports an error at line 25 in onsets_and_frames/decoding.py.
Since '-' operation between two bool tensors is deprecated, can I simply replace A - B with (A ^ B) | (A & B)?

**Comment by jongwook** [comment]
Thanks for catching that! I think `A & ~B` will give an equivalent result.

**Comment by kme2698** [comment]
To make sure, do you mean if A = tensor of False and B = tensor of True, the result should be the tensor of False?
Thank you for the fast reply!

**Comment by jongwook** [comment]
Yes, because it is supposed to detect the 'rising edges' of the onset.

This was due to a breaking change in PyTorch where boolean expressions that were returning `uint8` is now returning `bool`. [I've updated `decoding.py`](https://github.com/jongwook/onsets-and-frames/commit/12c62148bad8e7455b851bd50762fee5f65615f3) so that it'll continue using `uint8`.

Thanks again!
